// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddConnection(arg1) {
  return window['go']['main']['App']['AddConnection'](arg1);
}

export function DeleteConnection(arg1) {
  return window['go']['main']['App']['DeleteConnection'](arg1);
}

export function GetConnectionGroups() {
  return window['go']['main']['App']['GetConnectionGroups']();
}

export function GetConnections() {
  return window['go']['main']['App']['GetConnections']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetWSPort() {
  return window['go']['main']['App']['GetWSPort']();
}

export function StartSSHSession(arg1) {
  return window['go']['main']['App']['StartSSHSession'](arg1);
}

export function StopSSHSession(arg1) {
  return window['go']['main']['App']['StopSSHSession'](arg1);
}

export function TestConnection(arg1) {
  return window['go']['main']['App']['TestConnection'](arg1);
}

export function UpdateConnection(arg1, arg2) {
  return window['go']['main']['App']['UpdateConnection'](arg1, arg2);
}
