// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';

export function AddConnection(arg1:model.Connection):Promise<void>;

export function DeleteConnection(arg1:number):Promise<void>;

export function GetConnectionGroups():Promise<Array<string>>;

export function GetConnections():Promise<Array<model.Connection>>;

export function GetSettings():Promise<model.Settings>;

export function GetWSPort():Promise<number>;

export function StartSSHSession(arg1:number):Promise<string>;

export function StopSSHSession(arg1:string):Promise<void>;

export function TestConnection(arg1:number):Promise<void>;

export function UpdateConnection(arg1:number,arg2:model.Connection):Promise<void>;
